# This tests that access modifier properties are appearing on a Class
# Paul Worrall, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX net.interition.sparqlycode.testsuite: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>
PREFIX java.lang: <http://www.interition.net/sparqlycode/id/java/lang/>


ASK WHERE { 

     net.interition.sparqlycode.testsuite:AccessModifiersOnClass java:access ?access .

}