
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements.  See the NOTICE file distributed with
 # this work for additional information regarding copyright ownership.
 # The ASF licenses this file to You under the Apache License, Version 2.0
 # (the "License"); you may not use this file except in compliance with
 # the License.  You may obtain a copy of the License at
 # 
 #      http://www.apache.org/licenses/LICENSE-2.0
 # 
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.


# This test that return types that are arrays have dimension properties
# Paul Worrall, Interition Ltd.

# expecting:
#  doSomething() to have an argument of String[]
#  getNames() to has an argument of String[] and a return type of String[]

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX net.interition.sparqlycode.testsuite: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE { 
	
   		net.interition.sparqlycode.testsuite:MethodArgumentExercise java:method ?method .
   		?method rdfs:label "getNames" ;
   		       java:returns ?return .
   		?return java:dimension ?dimension .
		filter ( ?dimension = 1 ) 
   		
}


