# This tests that methods marked as Deprecated are discoverable
# Paul Worrall, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX jdk: <http://www.interition.net/sparqlycode/id/>
PREFIX net.interition.sparqlycode.testsuite: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>
PREFIX java.lang: <http://www.interition.net/sparqlycode/id/java/lang/>

ASK WHERE { 

     net.interition.sparqlycode.testsuite:FieldTests java:field ?field .
     ?field java:type jdk:int  .

}