# Test that sparqlycode reflects a wildcard type with extends bound 

PREFIX sc:   <http://www.interition.net/sparqlycode/id/>
PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>

ASK WHERE {

	SELECT (COUNT(?extends) AS ?number)  
          WHERE  {  
            subject:GenericMethodExercise java:method ?method .
            ?method rdfs:label "wildecardReturn" .
            ?method java:returns ?returns .
            ?returns java:typeParameter ?typeParameter .
            ?typeParameter java:argument ?argument .
            ?argument java:extends ?extends .
			}
	 	HAVING ( ?number = 2 )

}
