# Test that sparqlycode reflects a wildcard type with extends bound 

PREFIX sc:   <http://www.interition.net/sparqlycode/id/>
PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>

ASK WHERE {

	SELECT (COUNT(?typeParameter) AS ?number)  
          WHERE  {  
          	subject:GenericMethodExercise java:method ?method .
            ?method rdfs:label "wildecardReturn" .
            ?method java:returns/java:typeParameter/java:argument/java:extends ?typeParameter .
			}
	 	HAVING ( ?number = 2 )

}
