# Method argument exercise test

PREFIX sc:   <http://www.interition.net/sparqlycode/id/>
PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net.interition.sparqlycode.testsuite.>

ASK WHERE {
     
     SELECT (COUNT(?method) AS ?number)  
          WHERE  {  
          	subject:MethodArgumentExercise java:method ?method .
            ?method java:argument ?argument .
            # second type is actually a string array and we missing the modelling if that!!!
            ?argument java:type <http://www.interition.net/sparqlycode/id/java.lang.String> .
          }
     HAVING ( ?number = 2 )

}
