# GenericMethodExercise must have one String parameter represented in the Sparqlycode
# This test needs to do something more specific for testing generics

PREFIX sc:   <http://www.interition.net/sparqlycode/id/>
PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>

ASK WHERE {
     
     SELECT (COUNT(?method) AS ?number)  
          WHERE  {  
          	subject:GenericMethodExercise java:method ?method .
            ?method rdfs:label "toList" .
            ?method java:argument/java:type <http://www.interition.net/sparqlycode/id/java/lang/String> .

          }
     HAVING ( ?number = 1 )

}
