# Finds any interface that only has constants in it, and no method declarations.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:AvoidConstantsInterface a java:Interface .
			subject:AvoidConstantsInterface java:field ?field .
			?field java:isStatic true .
			?field java:isFinal true .
			?field java:access "Public" .
			FILTER NOT EXISTS {subject:AvoidConstantsInterface java:method ?method} .
}
