# This finds abstract classes that have no methods in them whatsoever.
# NOTE: this excludes investigating constructors
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:AbstractClassWithoutAnyMethod java:isAbstract true .
			FILTER NOT EXISTS {
			  subject:AbstractClassWithoutAnyMethod java:method ?method
			} .
}  
