# Finds protected methods in final classes that don't extend other classes with protected methods.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:AvoidProtectedMethodInFinalClassNotExtending java:extends <http://www.interition.net/sparqlycode/id/java/lang/Object> .
			subject:AvoidProtectedMethodInFinalClassNotExtending java:isFinal true .
			subject:AvoidProtectedMethodInFinalClassNotExtending java:method ?method .
			?method java:access "Protected" .
}
