# This finds abstract classes that have no methods in them whatsoever.
# NOTE: this excludes investigating constructors
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
	SELECT (COUNT (?name) AS ?number)
		WHERE {
			subject:AbstractClassWithoutAnyMethod java:isAbstract true .
			subject:AbstractClassWithoutAnyMethod rdfs:label ?name .
			FILTER NOT EXISTS {subject:AbstractClassWithoutAnyMethod java:method ?method} .
		} HAVING (?number = 0)
}  
