# This finds protected fields declared in final classes. These fields should not be protected as a final class cannot have subclasses.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE{
			subject:AvoidProtectedFieldInFinalClass java:isFinal true .
			subject:AvoidProtectedFieldInFinalClass java:field ?field .
			?field java:access "Protected" .
} 
