# Finds methods that are declared to be synchronized. Synchronization should be used at block-level.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:AvoidSynchronizedAtMethodLevel java:method ?method .
			?method java:isSynchronized true .
}
