# This finds all classes with a bad clone implementation - should use super.clone()
# this is nto working yet

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.example.org/>

SELECT ?classes ?method ?return WHERE
 {  
    ?classes java:method ?method .
    ?method rdfs:label "clone" .
    optional { ?method java:returns ?return .}
    
} LIMIT 100