# Finds classes with a name starting with a lower case letter.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:classNamingConventions rdfs:label ?className
			FILTER (REGEX (?className,  "^[a-z]"))
}
