# Finds classes that extend Thread or implement Runnable.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject1: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX subject2: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/DoNotUseThreads/>

ASK WHERE {
	SELECT (COUNT(?className) AS ?number)
		WHERE {
			{
				subject1:DoNotUseThreads java:extends <http://www.interition.net/sparqlycode/id/java/lang/Thread> .
				subject1:DoNotUseThreads rdfs:label ?className .
			}
		UNION {
				subject2:RunnableImplementation java:implements <http://www.interition.net/sparqlycode/id/java/lang/Runnable> .
				subject2:RunnableImplementation rdfs:label ?className .
			}
		} HAVING (?number = 0)
}