# Finds classes that extend Thread or implement Runnable.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject1: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX subject2: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/DoNotUseThreads/>

ASK WHERE {
			{
				subject1:DoNotUseThreads java:extends <http://www.interition.net/sparqlycode/id/java/lang/Thread> .
			}
		UNION {
				subject2:RunnableImplementation java:implements <http://www.interition.net/sparqlycode/id/java/lang/Runnable> .
			}
}