# Finds classes that import any sun utilities (sun.*).
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
			subject:DontImportSun java:imports ?imports .
			subject:DontImportSun rdfs:label ?className
			FILTER (STRSTARTS(STR(?imports), "http://www.interition.net/sparqlycode/id/sun/"))
}