# This finds classes with an excessive number of public methods . Eg > 10
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>

ASK WHERE {
	SELECT (COUNT(?method) AS ?totalPublicMethods) 
		WHERE {  
    		subject:ExcessivePublicMethods java:method ?method .
    		?method java:access "Public" .

		} HAVING (?totalPublicMethods < 10)
}
