# This finds classes with an excessive number of public methods . Eg > 10
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
	SELECT (COUNT(?field) AS ?totalPublicFields) 
	WHERE {  
    	subject:ExcessivePublicFields java:field ?field .
    	?field java:access "Public" .
	} HAVING (?totalPublicFields < 10)
}