# Checks if there is a public overriding instance of the finalize() method. Access should be Protected.
# Returns False if finalize method not found to be Protected
# Adam Nogradi, Interition Ltd.
# Modified: Paul Worrall, ...

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sc: <http://www.interition.net/sparqlycode/id/>

ASK WHERE {
			subject:FinalizeShouldBeProtected java:method ?method .
			?method rdfs:label "finalize" ;
			      java:returns ?returnType .
			?returnType java:type sc:void .
			
			FILTER EXISTS { 
						?method java:access "Protected" ; java:argument ?arg .
			} .
}