# This finds any overloaded instances of the void finalize() method. It should not have any arguments.
# Returns True if it finds arguments
# Adam Nogradi, Interition Ltd.
# Modified: Paul Worrall

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sc: <http://www.interition.net/sparqlycode/id/>

ASK WHERE {

	subject:FinalizeOverloaded java:method ?method .
	?method rdfs:label "finalize" ;
		 java:returns/java:type sc:void .
	
	?method java:argument ?arg .

}
		
