# Finds any class that uses a tearDown method without the @After annotation.
# Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
	SELECT (COUNT(?methodName) AS ?number)
		WHERE {
			subject:JUnit4TestShouldUseAfterAnnotation java:method ?method .
			?method rdfs:label ?methodName .
			FILTER (?methodName = "tearDown")
			FILTER NOT EXISTS {?method java:hasAnnotation <http://www.interition.net/sparqlycode/id/org/junit/After>} .
		} HAVING (?number = 0)
}
