# This finds all classes that implement equals method but do not provide a hashCode method.
# Paul Worrall & Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE { 
	
   		subject:MissingHashCode rdfs:label ?className .
    	subject:MissingHashCode java:method ?method .
    	?method rdfs:label "equals" .
    	FILTER EXISTS {
    		subject:MissingHashCode java:method ?hashCode .
    		?hashCode rdfs:label "hashCode" .
   		}
}