# This finds all classes that implement hashCode method but do not provide an equals method
# Returns False when an equals triple is not found
# Paul Worrall & Adam Nogradi, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {

   		subject:MissingEquals rdfs:label ?className .
    	subject:MissingEquals java:method ?method .
    	?method rdfs:label "hashCode" .
    	FILTER EXISTS {
    	subject:MissingEquals java:method ?equals .
    		?equals rdfs:label "equals" .
   		}

}