# Finds classes with less than 5 characters in their name. Returns true when a result is returned due to matching the undesirable
# condition
# Adam Nogradi, Interition Ltd.
# Modifed: Paul Worrall, ...

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
			subject:SCN rdfs:label ?className .
			FILTER  (REGEX (?className,  "^.{0,4}$"))

}