# Finds methods explicitly/unnecessarily declared final inside final classes.
# Adam Nogradi, Interition Ltd.
# Paul Worrall, ...

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/pmdtestsuite/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {

			subject:UnnecessaryFinalModifier java:isFinal true ; java:method ?method .
			FILTER NOT EXISTS {
				  ?method java:isFinal true .
			  }
}