# this is for testing queries

PREFIX sc:   <http://www.interition.net/sparqlycode/id/>
PREFIX java: <http://www.interition.net/java/ref/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX subject: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>

SELECT * WHERE {

          	subject:GenericMethodExercise java:method ?method .
            ?method rdfs:label "wildecardReturn" .
            ?method java:returns/java:typeParameter/java:argument/java:extends ?extends .
            # check they have labels as well
            ?argument java:extends ?extends ; rdfs:label ?name .
            

}
