# test that the java:name property is no longer created by the sc engine
# Paul Worrall, Interition Ltd.

PREFIX java: <http://www.interition.net/java/ref/>
PREFIX net.interition.sparqlycode.testsuite: <http://www.interition.net/sparqlycode/id/net/interition/sparqlycode/testsuite/>
PREFIX java.lang: <http://www.interition.net/sparqlycode/id/java/lang/>


ASK WHERE { 

     ?class a java:Class .
     ?class java:name ?name .

}
